create table users (
	id int auto_increment,
    username varchar(60) not null unique,
	password varchar(60) not null,
	email varchar(255) unique,
    created_at datetime default now(),
    primary key (id)
    );
    
create table chirps (
	id int auto_increment,
	userid int not null,
	content varchar(255) not null,
    location varchar(50) not null,
	created_at datetime default now(),
	primary key (id),
	foreign key (userid) references users (id)
    );
    
create table mentions (
	chirpid int not null,
	userid int not null,
	primary key (chirpid, userid),
	foreign key (userid) references users (id),
	foreign key (chirpid) references chirps (id) 
    );
    
    
    insert into users (username, email, password) values
    ('Username1', 'Username1@email.com', 'password123'),
    ('Username2', 'Username2@email.com', 'password123'),
    ('Username3', 'Username3@email.com', 'password123'),
    ('Username4', 'Username4@email.com', 'password123'),
    ('Username5', 'Username5@email.com', 'password123'),
    ('Username6', 'Username6@email.com', 'password123'),
    ('Username7', 'Username7@email.com', 'password123'),
    ('Username8', 'Username8@email.com', 'password123'),
    ('Username9', 'Username9@email.com', 'password123'),
    ('Username10', 'Username10@email.com', 'password123');
    
    insert into chirps (userid, content, location) values
    (1, 'This is some chirp text 1.', 'Home'),
    (1, 'This is some chirp text 2.', 'Home'),
    (1, 'This is some chirp text 3.', 'Home'),
    (1, 'This is some chirp text 4.', 'Home'),
    (1, 'This is some chirp text 5.', 'Home'),
    (1, 'This is some chirp text 6.', 'Home'),
    (1, 'This is some chirp text 7.', 'Home'),
    (1, 'This is some chirp text 8.', 'Home'),
    (1, 'This is some chirp text 9.', 'Home'),
    (1, 'This is some chirp text 10.', 'Home'),
    (2, 'This is some chirp text 1.', 'Home'),
    (2, 'This is some chirp text 2.', 'Home'),
    (2, 'This is some chirp text 3.', 'Home'),
    (2, 'This is some chirp text 4.', 'Home'),
    (2, 'This is some chirp text 5.', 'Home'),
    (2, 'This is some chirp text 6.', 'Home'),
    (2, 'This is some chirp text 7.', 'Home'),
    (2, 'This is some chirp text 8.', 'Home'),
    (2, 'This is some chirp text 9.', 'Home'),
    (2, 'This is some chirp text 10.', 'Home'),
    (3, 'This is some chirp text 1.', 'Home'),
    (3, 'This is some chirp text 2.', 'Home'),
    (3, 'This is some chirp text 3.', 'Home'),
    (3, 'This is some chirp text 4.', 'Home'),
    (3, 'This is some chirp text 5.', 'Home'),
    (3, 'This is some chirp text 6.', 'Home'),
    (3, 'This is some chirp text 7.', 'Home'),
    (3, 'This is some chirp text 8.', 'Home'),
    (3, 'This is some chirp text 9.', 'Home'),
    (3, 'This is some chirp text 10.', 'Home'),
    (4, 'This is some chirp text 1.', 'Home'),
    (4, 'This is some chirp text 2.', 'Home'),
    (4, 'This is some chirp text 3.', 'Home'),
    (4, 'This is some chirp text 4.', 'Home'),
    (4, 'This is some chirp text 5.', 'Home'),
    (4, 'This is some chirp text 6.', 'Home'),
    (4, 'This is some chirp text 7.', 'Home'),
    (4, 'This is some chirp text 8.', 'Home'),
    (4, 'This is some chirp text 9.', 'Home'),
    (4, 'This is some chirp text 10.', 'Home'),
    (5, 'This is some chirp text 1.', 'Home'),
    (5, 'This is some chirp text 2.', 'Home'),
    (5, 'This is some chirp text 3.', 'Home'),
    (5, 'This is some chirp text 4.', 'Home'),
    (5, 'This is some chirp text 5.', 'Home'),
    (5, 'This is some chirp text 6.', 'Home'),
    (5, 'This is some chirp text 7.', 'Home'),
    (5, 'This is some chirp text 8.', 'Home'),
    (5, 'This is some chirp text 9.', 'Home'),
    (5, 'This is some chirp text 10.', 'Home'),
    (6, 'This is some chirp text 1.', 'Home'),
    (6, 'This is some chirp text 2.', 'Home'),
    (6, 'This is some chirp text 3.', 'Home'),
    (6, 'This is some chirp text 4.', 'Home'),
    (6, 'This is some chirp text 5.', 'Home'),
    (6, 'This is some chirp text 6.', 'Home'),
    (6, 'This is some chirp text 7.', 'Home'),
    (6, 'This is some chirp text 8.', 'Home'),
    (6, 'This is some chirp text 9.', 'Home'),
    (6, 'This is some chirp text 10.', 'Home'),
    (7, 'This is some chirp text 1.', 'Home'),
    (7, 'This is some chirp text 2.', 'Home'),
    (7, 'This is some chirp text 3.', 'Home'),
    (7, 'This is some chirp text 4.', 'Home'),
    (7, 'This is some chirp text 5.', 'Home'),
    (7, 'This is some chirp text 6.', 'Home'),
    (7, 'This is some chirp text 7.', 'Home'),
    (7, 'This is some chirp text 8.', 'Home'),
    (7, 'This is some chirp text 9.', 'Home'),
    (7, 'This is some chirp text 10.', 'Home'),
    (8, 'This is some chirp text 1.', 'Home'),
    (8, 'This is some chirp text 2.', 'Home'),
    (8, 'This is some chirp text 3.', 'Home'),
    (8, 'This is some chirp text 4.', 'Home'),
    (8, 'This is some chirp text 5.', 'Home'),
    (8, 'This is some chirp text 6.', 'Home'),
    (8, 'This is some chirp text 7.', 'Home'),
    (8, 'This is some chirp text 8.', 'Home'),
    (8, 'This is some chirp text 9.', 'Home'),
    (8, 'This is some chirp text 10.', 'Home'),
    (9, 'This is some chirp text 1.', 'Home'),
    (9, 'This is some chirp text 2.', 'Home'),
    (9, 'This is some chirp text 3.', 'Home'),
    (9, 'This is some chirp text 4.', 'Home'),
    (9, 'This is some chirp text 5.', 'Home'),
    (9, 'This is some chirp text 6.', 'Home'),
    (9, 'This is some chirp text 7.', 'Home'),
    (9, 'This is some chirp text 8.', 'Home'),
    (9, 'This is some chirp text 9.', 'Home'),
    (9, 'This is some chirp text 10.', 'Home'),
    (10, 'This is some chirp text 1.', 'Home'),
    (10, 'This is some chirp text 2.', 'Home'),
    (10, 'This is some chirp text 3.', 'Home'),
    (10, 'This is some chirp text 4.', 'Home'),
    (10, 'This is some chirp text 5.', 'Home'),
    (10, 'This is some chirp text 6.', 'Home'),
    (10, 'This is some chirp text 7.', 'Home'),
    (10, 'This is some chirp text 8.', 'Home'),
    (10, 'This is some chirp text 9.', 'Home'),
    (10, 'This is some chirp text 10.', 'Home');
 
    select * from users;
    select * from mentions;
    select 
		users.username,
        chirps.*
    from chirps
    join users on users.id = chirps.userid;